version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres_16
#    command:
#      - "postgres"
#      - "-c"
#      - "config_file=/var/lib/postgresql/data/postgresql.conf"
    networks:
      - docker-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
#      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    restart: unless-stopped

networks:
  docker-network:
    driver: bridge
