"""on_delete_cascade_for_yandex_acc_id

Revision ID: 5b7f91883360
Revises: d49fd35ace93
Create Date: 2025-03-30 14:48:49.064568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7f91883360'
down_revision: Union[str, None] = 'd49fd35ace93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fk_user_yandex_account_table_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_fk_user_yandex_account_table_id_fkey', 'users', 'yandex_account_table', ['fk_user_yandex_account_table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fk_user_yandex_account_table_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_fk_user_yandex_account_table_id_fkey', 'users', 'yandex_account_table', ['fk_user_yandex_account_table_id'], ['id'])
    # ### end Alembic commands ###
