"""create_user_yandex_account_table_fk

Revision ID: 8f71b10596ca
Revises: 883e5325d165
Create Date: 2025-03-29 22:02:47.526274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f71b10596ca'
down_revision: Union[str, None] = '883e5325d165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fk_user_yandex_account_table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'yandex_account_table', ['fk_user_yandex_account_table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'fk_user_yandex_account_table_id')
    # ### end Alembic commands ###
