"""user_fk_for_file

Revision ID: b66edaba9d78
Revises: e0d8050dc083
Create Date: 2025-03-29 18:44:22.946419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66edaba9d78'
down_revision: Union[str, None] = 'e0d8050dc083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_storage', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('file_storage_user_id_fk', 'file_storage', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_storage_user_id_fk', 'file_storage', type_='foreignkey')
    op.drop_column('file_storage', 'user_id')
    # ### end Alembic commands ###
