"""file_storage_ondele_cascade_user_id

Revision ID: c0dd009d770c
Revises: 2035b12f8ba4
Create Date: 2025-03-30 17:39:29.743056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c0dd009d770c"
down_revision: Union[str, None] = "2035b12f8ba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_storage_user_id_fk", "file_storage", type_="foreignkey")
    op.create_foreign_key(
        "file_storage_user_id_fk",
        "file_storage",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_fk_user_yandex_account_table_id_fkey", "users", type_="foreignkey"
    )
    op.create_foreign_key(
        "users_fk_user_yandex_account_table_id_fkey",
        "users",
        "yandex_account_table",
        ["fk_user_yandex_account_table_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
